### ISSUE TITLE
Flash bootloader on rk3288 too?

### ISSUE THREAD

**Issue by phhusson** [rockchip-linux/build#1]
In 0c521b46b64ff33cf0274f0da392b405931ab57b, flash_tool.sh enables to write SPL in addition to further data, for rk3399
Though this might not be needed only on rk3399.

For instance, I am using an rk3288 TVBox, with original rk3288 sdk for Android 4.4, which doesn't know GPT. For first bring-up of this "Linux SDK", I had to flash a new u-boot.

Perhaps this doesn't need a change to flash_tool.sh, but at least write it in some documentation.

**Comment by wzyy2** [comment]
rk3288 don't need to flash rk-miniloader.
The reason why rk3399 do this is that rk3399 don't have spl support before, so it have to flash binary miniloader as the first stage loader. I have update uboot branch which have rk3399 spl support, so this step will be removed.

rk3288 boot sequence:
uboot spl -> uboot.bin
rk3399 boot sequence:
rk miniloader-> uboot.bin

**Comment by wzyy2** [comment]
For first bring-up of this "Linux SDK", i think you don't have to flash additional
 miniloader becuase uboot spl is included in system image.

https://github.com/rockchip-linux/build/blob/debian/mk-image.sh#L99
I had try to write miniloader like spl but i failed, it seems miniloader image will be separated by upgrade_tool.

**Comment by phhusson** [comment]
I don't think SPL is booted from "system image"

I tried to WL 0 zero.img, where zero.img is a 256MB files full of 0
and I stil had SPL booting into rockusb mode (I did check it wasn't maskrom)

**Comment by wzyy2** [comment]
I have done the experiment before, it seems upgrade_tool will skip "zero" block, so when you write a zero.img, it will be ignored. 

Could your board bring-up by just flashing system.img?

I'm also confused about those boot things.  If you have done any experiment, please share with me. : )

**Comment by phhusson** [comment]
Obviously, calling the scripts the dump way is what I did first ;)
To clear any doubts, I'll redo the migration

**Comment by phhusson** [comment]
What I did:
Flash back an Android 4.4 to the board (a BX20 fwiw)
Boot with "rockusb button"
Call sudo bash build/flash_tool.sh   -c rk3288 -p system  -i  out/system.img
And then I get greeted by: https://gist.github.com/phhusson/4792652e396c1a22fc2c6bd2d146b4d8
Which basically says it is still the old bootloader running, and that it can't find any partition

But booting into MaskRom and calling again the same shell script is ok.
So at the end I guess that the only thing needed is to mention in README.md that you might need to boot into maskrom before flashing

**Comment by wzyy2** [comment]
Ok, i forget to mention it in README.md

**Comment by wzyy2** [comment]
https://github.com/rockchip-linux/build/commit/fe9c6cded1c6f812955b8853c3664772ca408d37
