### ISSUE TITLE
Wrong u-boot defconfig filename for miniarm board in board_configs.sh

### ISSUE THREAD

**Issue by gooze74** [rockchip-linux/build#3]
The u-boot defconfig filename is wrong for miniarm board. The miniarm-rk3288_defconfig file does not exist in your u-boot repo.
Please update line 50 of board_configs.sh file from :
UBOOT_DEFCONFIG=miniarm-rk3288_defconfig
to : 
UBOOT_DEFCONFIG=tinker-rk3288_defconfig

Thanks

**Comment by wzyy2** [comment]
https://github.com/rockchip-linux/build/commit/8420003be97e859967c75ca43ddb6b3421c5255f
