### ISSUE TITLE
Only one board type are handled per chip for dtb filename in rk3288.conf

### ISSUE THREAD

**Issue by gooze74** [rockchip-linux/build#4]
Depending on the board type built for the rk3288 chip, the dtb change depending on the board type name. However, in the rk3288.conf, it is hardcoded as "rk3288-evb-act8846.dtb".
If building other board for rk3288, the build image script will not work (miniarm for me).

**Comment by wzyy2** [comment]
https://github.com/rockchip-linux/build/commit/ccebf329825d9273b32574320445ebc5deb26c4a
