### ISSUE TITLE
Missing DTB file ERROR when building kernel image for  rk3288-evb

### ISSUE THREAD

**Issue by ArneKorsika** [rockchip-linux/build#5]
There is a error occurring when using ```build/mk-kernel.sh rk3288-evb``` command to build a kernel image for RK3288 dev board with act8846 PMU. The script doesn't successfully build an image since it can't find the DTB file.  I found out that this is due to the wrong file being specified in ```board_configs.sh``` and ```extlinux/rk3288.conf```. The ```board_configs.sh``` and the ```extlinux/rk3288.conf``` refers to ```rk3288-evb-act8846.dtb``` but this file doesn't exists in the Rockchip Kernel, however the ```rk3288-evb-act8846-edp.dtb``` file does. So what I did was replace the ```rk3288-evb-act8846.dtb``` with ```rk3288-evb-act8846-edp.dtb``` and I was able to build kernel and after that the system.img. I've flashed eMMC with ```build/flash_tool.sh``` and the evb  worked normally. 

----------------------------------------------------------------------------------------------------------------------------------
### NOW:
board_configs.sh
```
"rk3288-evb")
    DEFCONFIG=rockchip_linux_defconfig
    UBOOT_DEFCONFIG=evb-rk3288_defconfig
    DTB=rk3288-evb-act8846.dtb
    CHIP="rk3288"
;;
```

rk3288.conf
```
label kernel-4.4
    kernel /zImage
    fdt /rk3288-evb-act8846.dtb
    append  earlyprintk console=tty1 console=ttyS2,115200n8 rw root=/dev/mmcblk2p7 rootfstype=ext4 init=/sbin/init
```

----------------------------------------------------------------------------------------------------------------------------------
### MY FIX:

board_configs.sh
```
"rk3288-evb")
    DEFCONFIG=rockchip_linux_defconfig
    UBOOT_DEFCONFIG=evb-rk3288_defconfig
    DTB=rk3288-evb-act8846-edp.dtb
    CHIP="rk3288"
;;
```

rk3288.conf
```
label kernel-4.4
    kernel /zImage
    fdt /rk3288-evb-act8846-edp.dtb
    append  earlyprintk console=tty1 console=ttyS2,115200n8 rw root=/dev/mmcblk2p7 rootfstype=ext4 init=/sbin/init
```

**Comment by wzyy2** [comment]
That dts have been renamed for android.
If you want to use it, there is a patch https://github.com/rockchip-linux/meta-rockchip/blob/master/recipes-kernel/linux/linux-rockchip/0001-arm-dts-rk3288-evb-back-to-linux.patch.
