### ISSUE TITLE
Flash_tool dd:writing,Input/output error

### ISSUE THREAD

**Issue by redknight1056** [rockchip-linux/build#8]
Hello.

I'm trying to use the ./flash_tool.sh and I go nothing but "dd: writing to '/dev/sdb/: Input/output error" after about 6%

After that, the SD card is unreadable and requires re-formating.

Is there some way to fault find this? I have tried two new cards  8GB and 16GB Micro SDHC but the same issue is there. 

Is there also any other programs I need on my system to run the flash_tool script successfully?

System Info: Ubuntu 16.04 LTS 3GB RAM running for VirtualBox. The SD card interface is done from a Transcend Memory card to USB reader/writer.

Thank you for your time.

**Comment by wzyy2** [comment]
Could you revert this commit?
https://github.com/rockchip-linux/build/commit/e228de946bf1a008f3db24c603c7c1c52ad0d71b

**Comment by redknight1056** [comment]
Thank you, The ./flash.tool.sh now works
